config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<h2>Edit:</h2>
<%= render 'form' %>
<%= link_to "Cancel Edit", task_path(@task) %>

app/views/tasks/index.html.erb
<h2>Tasks</h2>

<% @tasks.each do |task| %>
  <h3><%= task.title %></h3>

  <p><%= task.completed %></p>

  <%= link_to "More details", task_path(task.id) %>
  <br>
  ====================
<% end %>
<br>
<%= link_to "Add Task", "tasks/new" %>

app/views/tasks/new.html.erb
<h2>New Task</h2>
<%= render "form" %>
<%= link_to "Cancel Creation", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h1>
<h3><%= @task.completed %></h4>


<%= link_to "Edit the task", edit_task_path(@task) %> <br>
<%= link_to "Delete the task", task_path(@task), method: :delete %> <br>
<%= link_to "List Tasks", tasks_path %>